// <auto-generated />
using AssetInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetInfo.API.Migrations
{
    [DbContext(typeof(AssetInfoContext))]
    partial class AssetInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssetInfo.API.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetSeriesNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetName = "Cutter head",
                            AssetSeriesNo = "S6",
                            MachineType = "C300"
                        },
                        new
                        {
                            Id = 2,
                            AssetName = "Cutter head",
                            AssetSeriesNo = "S7",
                            MachineType = "C40"
                        },
                        new
                        {
                            Id = 3,
                            AssetName = "Blade safety cover",
                            AssetSeriesNo = "S10",
                            MachineType = "C300"
                        },
                        new
                        {
                            Id = 4,
                            AssetName = "Blade safety cover",
                            AssetSeriesNo = "S11",
                            MachineType = "C60"
                        },
                        new
                        {
                            Id = 5,
                            AssetName = "Deburring blades",
                            AssetSeriesNo = "S6",
                            MachineType = "C300"
                        },
                        new
                        {
                            Id = 6,
                            AssetName = "Cutter head",
                            AssetSeriesNo = "S8",
                            MachineType = "C60"
                        },
                        new
                        {
                            Id = 7,
                            AssetName = "Clamping fixture",
                            AssetSeriesNo = "S2",
                            MachineType = "C60"
                        },
                        new
                        {
                            Id = 8,
                            AssetName = "Blade safety cover",
                            AssetSeriesNo = "S11",
                            MachineType = "C40"
                        },
                        new
                        {
                            Id = 9,
                            AssetName = "Shutter gripper",
                            AssetSeriesNo = "S3",
                            MachineType = "C40"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
